### ISSUE TITLE
Colored Emails Plus Zimlet not available in 8.5 and on

### ISSUE THREAD

**Issue by dploeger** [Zimbra-Community/adopted#24]
Because of this [zimbra issue](https://bugzilla.zimbra.com/show_bug.cgi?id=95344), the colored emails plus zimlet currently doesn't support Zimbra 8.5 and up.

**Comment by barrydegraaff** [comment]
It seems like this is patched in 8.7, however, it looks a bit ugly:
http://bugzilla-attach.zimbra.com/attachment.cgi?id=62962

Thats why I asked for the entire row te be changed of color:
https://bugzilla.zimbra.com/show_bug.cgi?id=95344#c19

result would be:
http://bugzilla-attach.zimbra.com/attachment.cgi?id=64674

**Comment by barrydegraaff** [comment]
The bug 95344 - getMailCellStyle is half fixed in 8.7 that aside, coloring emails is also available with core functionality.

https://blog.zimbra.com/2015/08/know-message-color/
https://wiki.zimbra.com/wiki/Zimbra_Web_Client_Mail_Filters

![message_5f00_color](https://cloud.githubusercontent.com/assets/4353213/13740256/0b36e960-e9d0-11e5-91f1-ff28f3e67a38.png)
![with_5f00_message_5f00_color](https://cloud.githubusercontent.com/assets/4353213/13740257/0b492530-e9d0-11e5-9fa0-02b7d900a032.png)

So I am closing this issue, and repo
